### ISSUE TITLE
unable to install pydoop on redhat, python 2.6

### ISSUE THREAD

**Issue by safire007** [crs4/pydoop#209]
Collecting pydoop
  Using cached pydoop-1.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    using setuptools version 20.2.2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-4Twx3F/pydoop/setup.py", line 65, in <module>
        import pydoop
      File "/tmp/pip-build-4Twx3F/pydoop/pydoop/**init**.py", line 42, in <module>
        _HADOOP_INFO = _PATH_FINDER.find()  # fill the cache ASAP
      File "/tmp/pip-build-4Twx3F/pydoop/pydoop/hadoop_utils.py", line 624, in find
        info[a] = getattr(self, a)()
      File "/tmp/pip-build-4Twx3F/pydoop/pydoop/hadoop_utils.py", line 433, in hadoop_home
        _hadoop_home_from_version_cmd() or
      File "/tmp/pip-build-4Twx3F/pydoop/pydoop/hadoop_utils.py", line 394, in _hadoop_home_from_version_cmd
        output = sp.check_output([hadoop_exec, 'version'])
    AttributeError: 'module' object has no attribute 'check_output'

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-4Twx3F/pydoop/

plzzzzzz help me in solving it.

**Comment by ilveroluca** [comment]
You're using an unsupported version of Python.  You need Python 2.7.

**Comment by safire007** [comment]
I am running the code on  cloudera CDH5 and it has only python 2.6. Is
there anyway that this library can be made to work on python  2.6 :/

**Comment by ilveroluca** [comment]
CDH5 doesn't impose a Python version (we test on CDH5 on [travis-ci](https://travis-ci.org/crs4/pydoop)).  If you can install Python 2.7 on your cluster then you should be able to run Pydoop.
